services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - ./.env
    restart: unless-stopped

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    env_file:
      - ./.env
    restart: unless-stopped