services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./.env
    restart: unless-stopped

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "9001:9001"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./.env
    restart: unless-stopped
