services:
  frontend:
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
    env_file:
      - ./.env
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "9001:9001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./.env
    restart: unless-stopped
