services:
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
    env_file:
      - ./.env
    restart: unless-stopped

  # frontend:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #   env_file:
  #     - ./.env
  #   restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "9001:9001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./.env
    restart: unless-stopped
